#site stettings
title: Méthodes, enjeux et limites de l'évaluation des tableaux de bord d’apprentissage
subtitle: "Atelier RJC EIAH 2026"
baseurl: "https://padlad.github.io/RJC-EIAH2026/"
url:  "https://padlad.github.io/RJC-EIAH2026/"

# build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
